### PR TITLE
allow capitalization of .md extension, see details for more info

### PR DESCRIPTION
**Pull request by fgotzens**
I've often seen people creating a "README.MD" file, instead of a "README.md". The former one would not be processed by the markdown-viewer.

### CODE REVIEW

**Comment by KeithLRobertson** [comment]
Very odd and surprising that the WebExt pattern matching is case-sensitive!
For (partial) completeness, shouldn't we include capitalized versions of all the extensions?
(I say partial, because this still wouldn't accept e.g. "README.Markdown", "R.MarkDown".)

**Comment by Cimbali** [comment]
I don’t think URLs match case-sensitively in general. Do you see this happening for local files?

**Comment by KeithLRobertson** [comment]
Yes, it's case-sensitive for local files. :-(  As I understand it, URLs are supposed to be case-insensitive on the scheme and authority, but case-sensitive on everything else.

**Comment by fgotzens** [comment]
> 
> 
> Very odd and surprising that the WebExt pattern matching is case-sensitive!
> For (partial) completeness, shouldn't we include capitalized versions of all the extensions?
> (I say partial, because this still wouldn't accept e.g. "README.Markdown", "R.MarkDown".)

Yeah, sure we could, I mean kind of... I also thought about that, but I decided to just put in `.MD` instead of all the other extensions since I've almost never seen anyone using one of the others...

Is maybe some function available in WebExt to case-lowerize the scanned extensions (like `'LOREM IPSUM'.lower()` in Python) ? I'd be open for everything to help solve the problem.

**Comment by Cimbali** [comment]
I suppose we could ask Firefox for the option to match paths case-insensitively, and in the mean time match both lower-case and upper-case versions of all markdown file extensions as suggested by @KeithLRobertson. I do not think mixed-case file extensions come up that often. (I’m not sure if there’s anywhere we can find actual data on that.)

**Comment by fgotzens** [comment]
> 
> 
> I suppose we could ask Firefox for the option to match paths case-insensitively, and in the mean time match both lower-case and upper-case versions of all markdown file extensions as suggested by @KeithLRobertson. I do not think mixed-case file extensions come up that often. (I’m not sure if there’s anywhere we can find actual data on that.)

I completely agree!

**Pull request merged**
