### PR TITLE
Update v2

### PR DESCRIPTION
**Pull request by Cimbali**
This is a PR rebasing all changes from #98:
- render in extension page
- can force rendering an online document
- ext+view-markdown scheme 
- security improvements (mostly through sandboxed iframe, also CSP, stopped inline CSS injections)

And includes more:
- less permissions, dynamically granted
- can open local files without changing mime type
- render in worker (out of main context for responsiveness and long-term memory footprint, etc.)
- docs update for coherence, especially wrt page download, view source, etc. 
- “onboarding” page to present new features (for updates) or general workflow (new installs), especially with respect to optional permissions
- waiting visual feedback (spinner) for slow rendering pages (e.g. 7MB use case from #77)
- updates code linting

If you can have a look at it too @KeithLRobertson that would be great.

### CODE REVIEW

**Comment by Cimbali** [comment]
I’ve been trying to get a signed beta version of the add-on to upload here for people to test, but so far I’ve been waiting on AMO reviews for over 4 days now…

**Comment by KOLANICH** [comment]
>AMO reviews

I have heard Mozilla has eliminated review process for the addons that don't have a "recommended" shield (this one doesn't)...

**Comment by Cimbali** [comment]
I think not being “recommended” means we don’t get a manual review with extra scrutiny. There still is a process for other addons, it’s mostly automatic, and if it fails (which it likely did due to updated dependencies) then we have to wait for someone to validate it…

The few beta versions I made are in the queue. They sent an automatic email that says “Your submission is taking longer than usual to be reviewed and signed. This process could take a few extra hours and up to a couple of days.”

**Comment by Cimbali** [comment]
Here is the v2 beta (numbered 1.8.1.44) [markdown_viewer_webext-1.8.1.44.zip](https://github.com/KeithLRobertson/markdown-viewer/files/10492233/markdown_viewer_webext-1.8.1.44.zip)

The “legacy behaviour” box is not 100% accurate (mentioning permissions instead of the issues downloading `.md` files). Any further feedback welcome.

**Comment by Cimbali** [comment]
Merging as it seems this is the way forward anyway. Still tweaks to happen before releasing publicly. Thanks a lot @KOLANICH for all the work and new solutions.

**Comment by Cimbali** [comment]
New beta [available in this github artifact](https://github.com/Cimbali/markdown-viewer/suites/10582638869/artifacts/527085742)

**Pull request merged**
