### PR TITLE
Change the color of the text at download button to black

### LINKED ISSUE #68: Download button has almost the same color as its background
The text is white, while the background color is light grey. 
That makes it readable only when one hovers it (and even though it is very dificult)
See [screenshot](https://hugos-public-screenshots.s3.eu-central-1.amazonaws.com/issue_markdown_viewer.png).

### PR DESCRIPTION
**Pull request by hugotiburtino**
The current color is the same of button background color, what
makes it unreadable.

Resolves: #68

### CODE REVIEW

**Comment by Cimbali** [comment]
isn’t black the default color? I’m worried that hardcoding black will break some other color schemes, for example whatever setup caused someone to put it in grey.
- what happens if you don’t put a color, just deleting the line? Does it beome black?
- is there some way of inheriting a foreground color?

**Comment by hugotiburtino** [comment]
- the white (#eee) is already hardcoded (edit: I've said before light grey but it is actually white)
- deleting leads to the ugly default blue of anchor
- ok, I'll see later if it can inherit it or if there some other elegant solution

**Comment by hugotiburtino** [comment]
- Inheritance doesn't work, because its parent ("__markdown-viewer__tools") has the color #eee, namely white (or almost white, if one wants to be precise).
- Changing the color to black isn't going to break anything else, since it is used in a single element("#__markdown-viewer__download").

**Comment by Cimbali** [comment]
Ah the default is blue, I see. Indeed mostly white works on the menu background but not on buttons. This should be good o go.

**Pull request merged**
